### ISSUE TITLE
import error when trying to run the example on homepage

### ISSUE THREAD

**Issue by crayonfu** [microprediction/timemachines#13]
Hello, I pip installed timemachines 0.7.2 with python3.8.5 on Ubuntu 20.04 LTS successfully. I can import timemachines package. But can't run the example on homepage due to missing imports on the first line:

`from timemachines.skatertools.data import hospital_with_exog`
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-e7d8e2dd7f0b> in <module>
----> 1 from timemachines.skatertools.data import hospital_with_exog
      2 from timemachines.skatertools.visualization.priorplot import prior_plot
      3 import matplotlib.pyplot as plt
      4 
      5 # Get some data

ImportError: cannot import name 'hospital_with_exog' from 'timemachines.skatertools.data' (/home/crayonfu/myProjects/ts_test/bt_venv/lib/python3.8/site-packages/timemachines/skatertools/data/__init__.py)
```
I can't find the class of hospital_with_exog in the directory of timemachines/skatertools/data on github repo. Am I missing something here? Thank you.

**Comment by crayonfu** [comment]
nvm. I find the hospital_with_exog function in  timemachines/skatertools/data/real.py and can import it. maybe the example on the home page needs to be updated a bit.

**Comment by microprediction** [comment]
Thanks ... give me one second

**Comment by microprediction** [comment]
Horendous! I make k compulsory and forgot. 

Anyway should be fixed now... https://github.com/microprediction/timemachines/blob/main/README.md

Added [examples/basic_usage](https://github.com/microprediction/timemachines/tree/main/examples/basic_usage) too

**Comment by microprediction** [comment]
Closing. Hopefully, it works now. Sorry about that.
