### ISSUE TITLE
Documentation Question

### ISSUE THREAD

**Issue by omarsumadi** [microprediction/timemachines#26]
Hi,

Was looking to find any instance / mention of Confidence or Prediction Intervals - could have this wrong, just a novice here looking into your package.

Thanks!

**Comment by microprediction** [comment]
The skater returns a vector of numbers intended to represent one standard deviation. So for instance 

     x, x_std, x = f( .... )   # skater
     x_up = [ xi+xstdi for xi,xstdi in zip(x,xstd) ]

then very roughly 5 out of 6 should be below x_up.

**Comment by microprediction** [comment]
I've updated the readme so at least 'confidence interval' is searchable. Thanks for the suggestion.

**Comment by omarsumadi** [comment]
Thank you!
