### ISSUE TITLE
timemachines cannot be installed on python 3.9, package pathlib causes problems

### ISSUE THREAD

**Issue by KlausGlueckert** [microprediction/timemachines#92]
not sure if other people encounter this

`WARNING: Discarding https://files.pythonhosted.org/packages/3c/a7/573e6c37775848cd2f9d0fcdf9dd168739f6534e6624573a968f3838d436/pathlib-0.1.tar.gz#sha256=d09e494964125084d67132c42b9e61fa4b428fa0dd8ae7aa2fb25925eeabc3e0 (from https://pypi.org/simple/pathlib/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pathlib (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.97, 1.0, 1.0.1)
ERROR: No matching distribution found for pathlib`

**Comment by microprediction** [comment]
Thanks. pathlib is standard so this shouldn't cause you a headache. Sorry about that. Checking the setup. What ver Python are you using?

**Comment by microprediction** [comment]
Do me a favor and try it now. [0.14.24](https://github.com/microprediction/timemachines/releases/tag/v0.14.24)

**Comment by microprediction** [comment]
@KlausGlueckert are we good to close this ?

**Comment by KlausGlueckert** [comment]
thanks, it works again, you can close the ticket :) happy new year

**Comment by microprediction** [comment]
HNY
