### ISSUE TITLE
Not finding module named 'timemachines.skaters.ik'

### ISSUE THREAD

**Issue by jamjahal** [microprediction/timemachines#93]
hi,
I've tried loading the example in colab, and then locally in a new env.  Both times, when going through the example to instantiate and use a model with the following code

"""
from timemachines.skaters.localskaters import local_skater_from_name
f = local_skater_from_name('thinking_fast_and_slow')
f
"""

I get the following error:

"""
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/w5/yscn4zzs1y18mqqxft3z_gwh0000gn/T/ipykernel_86047/1074514103.py in <module>
----> 1 from timemachines.skaters.localskaters import local_skater_from_name
      2 f = local_skater_from_name('thinking_fast_and_slow')
      3 f

/opt/anaconda3/envs/timemachines/lib/python3.10/site-packages/timemachines/skaters/localskaters.py in <module>
     32 from timemachines.skaters.pycrt.allpycaretskaters import PYCRT_SKATERS
     33 from timemachines.skaters.kts.allkatsskaters import KATS_SKATERS
---> 34 from timemachines.skaters.ik.allikskaters import IK_SKATERS
     35 
     36 LOCAL_SKATERS = EMA_SKATERS + PROPHET_SKATERS + DIVINE_SKATERS + DLM_SKATERS + \

ModuleNotFoundError: No module named 'timemachines.skaters.ik'
"""

Any help with this error would be appreciated.  The previous lines in the colab notebook work, so it is able to import something from timemachines.

**Comment by iklasky** [comment]
@jamjahal Just merged a pr to address that. let me know if that still doesnt work.

**Comment by microprediction** [comment]
I've bravely pushed a new version to PyPI that should fix this

**Comment by microprediction** [comment]
if it doesn't, I have better peripheral vision in the slack. https://join.slack.com/t/microprediction/shared_invite/zt-10ad1yiec-Jgsjkit~~dwNnpvRzyBTaQ

**Comment by microprediction** [comment]
@jamjahal are we good to close this?

**Comment by jamjahal** [comment]
This appears to have solved my problem, I am no longer getting that error.  Thank you!
