### ISSUE TITLE
[bug] thinking fast and slow

### ISSUE THREAD

**Issue by mglowacki100** [microprediction/timemachines#98]
Hi,
Nice approach with "fast and slow" but I'm a little confused about: `https://github.com/microprediction/timemachines/blob/main/timemachines/skaters/simple/thinking.py`
namely functions `thinking_slow_and_fast` and `thinking_fast_and_slow` looks exactly the same:
```
def thinking_slow_and_fast(y :Y_TYPE, s:dict, k:int =1, a:A_TYPE =None, t:T_TYPE =None, e:E_TYPE =None)->([float] , Any , Any):
    """
           Apply defensive quickly moving average to residuals from a slowly moving average
    """
    return quickly_moving_hypocratic_residual_factory(y=y, s=s, k=k, a=a, t=t, e=e, f=slowly_moving_average)


def thinking_fast_and_slow(y :Y_TYPE, s:dict, k:int =1, a:A_TYPE =None, t:T_TYPE =None, e:E_TYPE =None)->([float] , Any , Any):
    """
          Apply defensive slowly moving average to residuals from a quickly moving average
    """
    return quickly_moving_hypocratic_residual_factory(y=y, s=s, k=k, a=a, t=t, e=e, f=slowly_moving_average)
```
maybe one of them should return: `slowly_moving_hypocratic_residual_factory(y=y, s=s, k=k, a=a, t=t, e=e, f=quickly_moving_average)` ?

**Comment by microprediction** [comment]
Thanks! Great catch I just fixed it
https://github.com/microprediction/timemachines/blob/main/timemachines/skaters/simple/thinking.py

**Comment by microprediction** [comment]
btw I see you are on numerai. Give this a spin https://www.microprediction.com/competitions/daily
